/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AfterGame;

import javax.swing.JPanel;
import java.util.LinkedList;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Chauntalle Schüle, Dominik Gryska, Ivan 
 */
public class Highscores extends JPanel {
    
    public static LinkedList<Highscore> highscores;
    /**
     * Creates new form Highscores1
     */
    public Highscores(Highscore playedHighscore) {
        JScrollPane scrollPane = new JScrollPane();
        JTable table = new JTable(new HighscoreTableModel(highscores));
        scrollPane.setViewportView(table);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
